### ISSUE TITLE
Webchanges —edit = error

### ISSUE THREAD

**Issue by notDavid** [mborsetti/webchanges#10]
Hi there,

I get this error on first run. Please advise, thank you :)

```
$ webchanges --edit
Traceback (most recent call last):
  File "/usr/local/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/webchanges/cli.py", line 162, in main
    first_run(command_config)
  File "/usr/local/lib/python3.8/dist-packages/webchanges/cli.py", line 112, in first_run
    YamlConfigStorage.write_default_config(command_config.config)
  File "/usr/local/lib/python3.8/dist-packages/webchanges/storage.py", line 245, in write_default_config
    config_storage = cls(None)
  File "/usr/local/lib/python3.8/dist-packages/webchanges/storage.py", line 198, in __init__
    super().__init__(filename)
  File "/usr/local/lib/python3.8/dist-packages/webchanges/storage.py", line 193, in __init__
    self.filename = Path(filename)
  File "/usr/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

```
$ webchanges --version
webchanges 3.6.0
```

**Comment by mborsetti** [comment]
So sorry for the bad experience. Version 3.6.1 has just been released to fix this issue.

Unfortunately I have been unable to test initial install and this one slipped through. I think I can correctly test now, so it won't happen in the future.

Thanks for reporting!

**Comment by notDavid** [comment]
Glad to help, and thank you for the quick fix! :-)
