### ISSUE TITLE
RuntimeError: Webhook server error: {"message": "Cannot send an empty message", "code": 50006

### ISSUE THREAD

**Issue by jprokos** [mborsetti/webchanges#33]
Trying to understand why the same job that sends text to pushover is not sending text via the webhook feature and Discord

Did a bit of googling and looking through the docs but must be missing some bit of info. Hoping you have some insight.

My Discord link has been edited.

```

{"status":1,"request":"e3b47349-c696-4e3c-a05b-ffe89565ce8e"}
2022-04-12 02:42:43,222 reporters[4497558976] INFO: Submitting with webhook (<class 'webchanges.reporters.WebhookReporter'>)
2022-04-12 02:42:43,226 reporters[4497558976] DEBUG: Sending request to webhook with text:1. NEW: 32_NASA LC Records

**job result text here**

2022-04-12 02:42:43,228 connectionpool[4497558976] DEBUG: Starting new HTTPS connection (1): discord.com:443
2022-04-12 02:42:43,389 connectionpool[4497558976] DEBUG: https://discord.com:443 "POST /api/webhooks/xxx/xxxxx HTTP/1.1" 400 58
Traceback (most recent call last):
  File "/Users/john/.pyenv/versions/3.10.3/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/cli.py", line 232, in main
    urlwatch_command.run()
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 682, in run
    self.urlwatcher.close()
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/main.py", line 115, in close
    self.report.finish(jobs_file=self.jobs_storage.filename)
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/handler.py", line 482, in finish
    ReporterBase.submit_all(self, self.job_states, duration, jobs_file)
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/reporters.py", line 214, in submit_all
    subclass(report, cfg, job_states, duration, jobs_file).submit()
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/reporters.py", line 1364, in submit
    res = self.submit_to_webhook(webhook_url, chunk)
  File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/reporters.py", line 1379, in submit_to_webhook
    raise RuntimeError(f'Webhook server error: {result.text}')
RuntimeError: Webhook server error: {"message": "Cannot send an empty message", "code": 50006}
```

**Comment by mborsetti** [comment]
Woah!

My hypothesis is that the "chunkifier" https://github.com/mborsetti/webchanges/blob/db79546c9d57c106d1a6f2ee486ce287a3daccc5/webchanges/util.py#L104-L142 is sending back an empty chunk for some obscure reason (corner case). It's probably impossible to to debug without the actual text (or some obscured form of it), as it passess all tests. 

Pushover will take the entire message, while for Discord it needs to be turned into chunks no longer than 2,000 characters each.

Will be happy to take a look if you can provide some anonymized version of the actual text.

**Comment by mborsetti** [comment]
OK, found the issue: the webhook has a different payload structure for Discord, so it wasn't working.  Ended up implementing a separate reporter for Discord with additional functionality. It should work now; it's available as a release candidate in the unreleased branch.

Would you be so kind to test it?  If so, you can install it with 

```
pip install git+https://github.com/mborsetti/webchanges.git@unreleased
```

The documentation for the new Discord reporter is at https://webchanges.readthedocs.io/en/unreleased/reporters.html#discord (oops, I just noticed that the alphabetical order needs to be restored; will fix).

Thanks!

**Comment by jprokos** [comment]
Thank you for making those changes! There are a few limitations with Pushover - mainly message length being clipped when more than one job is reported.

The instructions need some editing. I took a stab at changing from "webhooks" to "discord" for the reporter name after "webhooks" failed... and it's working.

I believe the reporter also requires a  `max_message_length: 2000` ?

As far as the `config.yaml` is concerned, do we need to keep all of the reporters listed even though they are not enabled? At some point when in debug mode I noticed that webchanges considered it malformed and reverted to a default config.yaml if some of the reporters were missing.

**Comment by jprokos** [comment]
Anyway to get links to show up in Discord as real web links?

**Comment by mborsetti** [comment]
Thanks.  The documentation was indeed rushed for this release candidate and will get cleaned up (thanks for the additional inputs) before final release.

Correct; you can remove the reporters not in use from `config.yaml`; the alert  listing missing keys is there in verbose mode to make it easier to understand what's going on for debugging purposes.

I personally am not a Discord user and don't know if/how clickable web links can be made; if you find out how, please share. Similarly the colorization was an upstream contribution and am surprised to read that it isn't working :(

**Comment by jprokos** [comment]
Just adding more info for those interested. The links and color are there when viewed in a browser - just not on the iOS Discord.app... yet.

> Markdown is not fully supported from computer to mobile. I'm sorry for any hassle.

> I know that we want to reach full parity between PC and Mobile and we have a lot of devs who use the platform so I hope sooner rather than later, but unfortunately I don't have any ETA on it.
