### ISSUE TITLE
KeyError: 'indent' on versions 3.9.2 and 3.10

### ISSUE THREAD

**Issue by CTassisF** [mborsetti/webchanges#37]
webchanges is broken for me since 3.9.2 and 3.10 were released. I had to revert to 3.9.1 to make it work again.

It is returning a `KeyError: 'indent'` error.

`3.10`:
```
$ pip3 install --upgrade 'webchanges[beautify,use_browser]'
Requirement already satisfied: webchanges[beautify,use_browser] in ./.local/lib/python3.9/site-packages (3.10)
Collecting webchanges[beautify,use_browser]
  Using cached webchanges-3.10-py3-none-any.whl (125 kB)
  Using cached webchanges-3.9.2-py3-none-any.whl (99 kB)
Requirement already satisfied: markdown2 in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (2.4.3)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from webchanges[beautify,use_browser]) (5.3.1)
Requirement already satisfied: platformdirs in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (2.5.2)
Requirement already satisfied: lxml in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (4.8.0)
Requirement already satisfied: cssselect in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (1.1.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from webchanges[beautify,use_browser]) (2.25.1)
Requirement already satisfied: msgpack in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (1.0.3)
Requirement already satisfied: html2text in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (2020.1.16)
Requirement already satisfied: playwright in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (1.21.0)
Requirement already satisfied: psutil in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (5.9.0)
Requirement already satisfied: beautifulsoup4 in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (4.11.1)
Requirement already satisfied: cssbeautifier in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (1.14.3)
Requirement already satisfied: jsbeautifier in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]) (1.14.3)
Requirement already satisfied: soupsieve>1.2 in ./.local/lib/python3.9/site-packages (from beautifulsoup4->webchanges[beautify,use_browser]) (2.3.2.post1)
Requirement already satisfied: editorconfig>=0.12.2 in ./.local/lib/python3.9/site-packages (from cssbeautifier->webchanges[beautify,use_browser]) (0.12.3)
Requirement already satisfied: six>=1.13.0 in /usr/lib/python3/dist-packages (from cssbeautifier->webchanges[beautify,use_browser]) (1.16.0)
Requirement already satisfied: websockets==10.1 in ./.local/lib/python3.9/site-packages (from playwright->webchanges[beautify,use_browser]) (10.1)
Requirement already satisfied: greenlet==1.1.2 in ./.local/lib/python3.9/site-packages (from playwright->webchanges[beautify,use_browser]) (1.1.2)
Requirement already satisfied: pyee==8.1.0 in ./.local/lib/python3.9/site-packages (from playwright->webchanges[beautify,use_browser]) (8.1.0)

$ webchanges -v --test 71
2022-05-03 11:05:41,344 cli[139931681302336] DEBUG: webchanges: 3.10 Copyright 2020- Mike Borsetti
2022-05-03 11:05:41,344 cli[139931681302336] DEBUG: CPython: 3.9.2 ('default', 'Feb 28 2021 17:03:44') GCC 10.2.1 20210110
2022-05-03 11:05:41,347 cli[139931681302336] DEBUG: System: Linux-5.10.0-13-amd64-x86_64-with-glibc2.31
2022-05-03 11:05:41,347 storage[139931681302336] DEBUG: Run-time SQLite library: 3.34.1
2022-05-03 11:05:41,347 storage[139931681302336] INFO: Opening permanent sqlite3 database file /home/cesar/.cache/webchanges/cache.db
2022-05-03 11:05:41,347 storage[139931681302336] DEBUG: Executing (perm) 'SELECT name FROM sqlite_master WHERE type='table';'
2022-05-03 11:05:41,348 storage[139931681302336] DEBUG: Creating temp sqlite3 database file in memory
2022-05-03 11:05:41,348 storage[139931681302336] DEBUG: Executing (temp) 'CREATE TABLE webchanges (uuid TEXT, timestamp REAL, msgpack_data BLOB)'
2022-05-03 11:05:41,348 main[139931681302336] INFO: Config file is /home/cesar/.config/webchanges/config.yaml
2022-05-03 11:05:41,348 main[139931681302336] INFO: Jobs file is /home/cesar/.config/webchanges/jobs.yaml
2022-05-03 11:05:41,348 main[139931681302336] INFO: Hooks file is /home/cesar/.config/webchanges/hooks.py
2022-05-03 11:05:41,348 main[139931681302336] INFO: Database file is /home/cesar/.cache/webchanges/cache.db
2022-05-03 11:05:41,348 main[139931681302336] INFO: Loading hooks file
2022-05-03 11:05:41,425 main[139931681302336] INFO: Loaded 83 jobs
2022-05-03 11:05:41,433 storage[139931681302336] INFO: The configuration file /home/cesar/.config/webchanges/config.yaml is missing directive(s); the following default values are being used:
display:
  error: true
  new: true
  unchanged: false
report:
  browser:
    enabled: false
    title: '[webchanges] {count} changes: {jobs}'
  discord:
    colored: true
    embed: true
    enabled: false
    max_message_length: null
    subject: '{count} changes: {jobs}'
    webhook_url: ''
  email:
    smtp:
      auth: true
      host: localhost
      insecure_password: ''
      port: 25
      starttls: true
      user: ''
  html:
    diff: unified
  ifttt:
    enabled: false
    event: ''
    key: ''
  mailgun:
    api_key: ''
    domain: ''
    enabled: false
    from_mail: ''
    from_name: ''
    region: us
    subject: '[webchanges] {count} changes: {jobs}'
    to: ''
  markdown:
    details: true
    footer: true
    minimal: false
  matrix:
    access_token: ''
    enabled: false
    homeserver: ''
    room_id: ''
  prowl:
    api_key: ''
    application: ''
    enabled: false
    priority: 0
    subject: '[webchanges] {count} changes: {jobs}'
  pushbullet:
    api_key: ''
    enabled: false
  pushover:
    app: ''
    device: null
    enabled: false
    priority: normal
    sound: spacealarm
    user: ''
  run_command:
    command: ''
    enabled: false
  stdout:
    color: true
    enabled: true
  text:
    details: true
    footer: true
    line_length: 75
    minimal: false
  tz: null
  webhook:
    enabled: false
    markdown: false
    max_message_length: null
    webhook_url: ''
  xmpp:
    enabled: false
    insecure_password: ''
    recipient: ''
    sender: ''
See documentation at https://webchanges.readthedocs.io//en/stable/configuration.html
2022-05-03 11:05:41,433 handler[139931681302336] INFO: Job 71: Processing job <url url='https://cloud.google.com/release-notes' ignore_cached=True index_number=71 filter=['beautify', 'html2text', 'strip'] max_tries=2
2022-05-03 11:05:41,433 storage[139931681302336] DEBUG: Executing (perm) 'SELECT msgpack_data, timestamp FROM webchanges WHERE uuid = ? ORDER BY timestamp DESC LIMIT 1' with ('950d9456b6ce57e0b8bfa3c791200214fcbaed6b',)
2022-05-03 11:05:41,436 connectionpool[139931681302336] DEBUG: Starting new HTTPS connection (1): cloud.google.com:443
2022-05-03 11:05:42,585 connectionpool[139931681302336] DEBUG: https://cloud.google.com:443 "GET /release-notes HTTP/1.1" 200 None
2022-05-03 11:05:42,705 filters[139931681302336] INFO: Job 71: Applying filter beautify, subfilter(s) {}
2022-05-03 11:05:43,325 handler[139931681302336] DEBUG: Job 71: Job ended with error; incrementing cumulative tries to 4 ('indent')
Traceback (most recent call last):
  File "/home/cesar/.local/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/cli.py", line 237, in main
    urlwatch_command.run()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 713, in run
    self.handle_actions()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 648, in handle_actions
    self.test_job(self.urlwatch_config.test_job)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 206, in test_job
    raise job_state.exception
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/handler.py", line 160, in process
    filtered_data = FilterBase.process(filter_kind, subfilter, self, filtered_data)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/filters.py", line 239, in process
    return filtercls(job_state.job, job_state).filter(data, subfilter)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/filters.py", line 396, in filter
    indent = subfilter['indent']
KeyError: 'indent'
```

`3.9.2`:
```
$ pip3 install --upgrade 'webchanges[beautify,use_browser]<3.10'
Requirement already satisfied: webchanges[beautify,use_browser]<3.10 in ./.local/lib/python3.9/site-packages (3.9.2)
Collecting webchanges[beautify,use_browser]<3.10
  Using cached webchanges-3.9.2-py3-none-any.whl (99 kB)
  Using cached webchanges-3.9.1-py3-none-any.whl (95 kB)
Requirement already satisfied: cssselect in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (1.1.0)
Requirement already satisfied: lxml in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (4.8.0)
Requirement already satisfied: msgpack in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (1.0.3)
Requirement already satisfied: html2text in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (2020.1.16)
Requirement already satisfied: markdown2 in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (2.4.3)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from webchanges[beautify,use_browser]<3.10) (5.3.1)
Requirement already satisfied: platformdirs in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (2.5.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from webchanges[beautify,use_browser]<3.10) (2.25.1)
Requirement already satisfied: pyppeteer in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (1.0.2)
Requirement already satisfied: jsbeautifier in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (1.14.3)
Requirement already satisfied: beautifulsoup4 in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (4.11.1)
Requirement already satisfied: cssbeautifier in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.10) (1.14.3)
Requirement already satisfied: soupsieve>1.2 in ./.local/lib/python3.9/site-packages (from beautifulsoup4->webchanges[beautify,use_browser]<3.10) (2.3.2.post1)
Requirement already satisfied: six>=1.13.0 in /usr/lib/python3/dist-packages (from cssbeautifier->webchanges[beautify,use_browser]<3.10) (1.16.0)
Requirement already satisfied: editorconfig>=0.12.2 in ./.local/lib/python3.9/site-packages (from cssbeautifier->webchanges[beautify,use_browser]<3.10) (0.12.3)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (4.64.0)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/lib/python3/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (1.6.0)
Requirement already satisfied: websockets<11.0,>=10.0 in /usr/local/lib/python3.9/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (10.2)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/lib/python3/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (1.4.4)
Requirement already satisfied: certifi>=2021 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (2021.10.8)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (8.2.2)
Requirement already satisfied: urllib3<2.0.0,>=1.25.8 in /usr/lib/python3/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.10) (1.26.5)

$ webchanges -v --test 71
2022-05-03 11:00:57,806 cli[140584012388160] DEBUG: webchanges: 3.9.2 Copyright 2020- Mike Borsetti
2022-05-03 11:00:57,806 cli[140584012388160] DEBUG: CPython: 3.9.2 ('default', 'Feb 28 2021 17:03:44') GCC 10.2.1 20210110
2022-05-03 11:00:57,808 cli[140584012388160] DEBUG: System: Linux-5.10.0-13-amd64-x86_64-with-glibc2.31
2022-05-03 11:00:57,808 storage[140584012388160] DEBUG: Run-time SQLite library: 3.34.1
2022-05-03 11:00:57,808 storage[140584012388160] INFO: Opening permanent sqlite3 database file /home/cesar/.cache/webchanges/cache.db
2022-05-03 11:00:57,809 storage[140584012388160] DEBUG: Executing (perm) 'SELECT name FROM sqlite_master WHERE type='table';'
2022-05-03 11:00:57,809 storage[140584012388160] DEBUG: Creating temp sqlite3 database file in memory
2022-05-03 11:00:57,809 storage[140584012388160] DEBUG: Executing (temp) 'CREATE TABLE webchanges (uuid TEXT, timestamp REAL, msgpack_data BLOB)'
2022-05-03 11:00:57,810 main[140584012388160] INFO: Config file is /home/cesar/.config/webchanges/config.yaml
2022-05-03 11:00:57,810 main[140584012388160] INFO: Jobs file is /home/cesar/.config/webchanges/jobs.yaml
2022-05-03 11:00:57,810 main[140584012388160] INFO: Hooks file is /home/cesar/.config/webchanges/hooks.py
2022-05-03 11:00:57,810 main[140584012388160] INFO: Database file is /home/cesar/.cache/webchanges/cache.db
2022-05-03 11:00:57,810 main[140584012388160] INFO: Loading hooks file
2022-05-03 11:00:57,810 main[140584012388160] INFO: Loading jobs from file
2022-05-03 11:00:57,849 main[140584012388160] INFO: Found 83 jobs
2022-05-03 11:00:57,857 storage[140584012388160] INFO: The configuration file /home/cesar/.config/webchanges/config.yaml is missing directive(s); the following default values are being used:
display:
  error: true
  new: true
  unchanged: false
report:
  browser:
    enabled: false
    title: '[webchanges] {count} changes: {jobs}'
  discord:
    colored: true
    embed: true
    enabled: false
    max_message_length: null
    subject: '{count} changes: {jobs}'
    webhook_url: ''
  email:
    smtp:
      auth: true
      host: localhost
      insecure_password: ''
      port: 25
      starttls: true
      user: ''
  html:
    diff: unified
  ifttt:
    enabled: false
    event: ''
    key: ''
  mailgun:
    api_key: ''
    domain: ''
    enabled: false
    from_mail: ''
    from_name: ''
    region: us
    subject: '[webchanges] {count} changes: {jobs}'
    to: ''
  markdown:
    details: true
    footer: true
    minimal: false
  matrix:
    access_token: ''
    enabled: false
    homeserver: ''
    room_id: ''
  prowl:
    api_key: ''
    application: ''
    enabled: false
    priority: 0
    subject: '[webchanges] {count} changes: {jobs}'
  pushbullet:
    api_key: ''
    enabled: false
  pushover:
    app: ''
    device: null
    enabled: false
    priority: normal
    sound: spacealarm
    user: ''
  run_command:
    command: ''
    enabled: false
  stdout:
    color: true
    enabled: true
  text:
    details: true
    footer: true
    line_length: 75
    minimal: false
  tz: null
  webhook:
    enabled: false
    markdown: false
    max_message_length: null
    webhook_url: ''
  xmpp:
    enabled: false
    insecure_password: ''
    recipient: ''
    sender: ''
See documentation at https://webchanges.readthedocs.io//en/stable/configuration.html
2022-05-03 11:00:57,857 handler[140584012388160] INFO: Job 71: Processing job <url url='https://cloud.google.com/release-notes' ignore_cached=True index_number=71 filter=['beautify', 'html2text', 'strip'] max_tries=2
2022-05-03 11:00:57,857 storage[140584012388160] DEBUG: Executing (perm) 'SELECT msgpack_data, timestamp FROM webchanges WHERE uuid = ? ORDER BY timestamp DESC LIMIT 1' with ('950d9456b6ce57e0b8bfa3c791200214fcbaed6b',)
2022-05-03 11:00:57,860 connectionpool[140584012388160] DEBUG: Starting new HTTPS connection (1): cloud.google.com:443
2022-05-03 11:00:58,593 connectionpool[140584012388160] DEBUG: https://cloud.google.com:443 "GET /release-notes HTTP/1.1" 200 None
2022-05-03 11:00:58,717 filters[140584012388160] INFO: Job 71: Applying filter beautify, subfilter(s) {}
2022-05-03 11:00:59,344 handler[140584012388160] DEBUG: Job 71: Job ended with error; incrementing cumulative tries to 4 ('indent')
Traceback (most recent call last):
  File "/home/cesar/.local/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/cli.py", line 237, in main
    urlwatch_command.run()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 712, in run
    self.handle_actions()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 646, in handle_actions
    self.test_job(self.urlwatch_config.test_job)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 212, in test_job
    raise job_state.exception
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/handler.py", line 160, in process
    filtered_data = FilterBase.process(filter_kind, subfilter, self, filtered_data)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/filters.py", line 239, in process
    return filtercls(job_state.job, job_state).filter(data, subfilter)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/filters.py", line 396, in filter
    indent = subfilter['indent']
KeyError: 'indent'
```

`3.9.1`:
```
$ pip3 install --upgrade 'webchanges[beautify,use_browser]<3.9.2'
Requirement already satisfied: webchanges[beautify,use_browser]<3.9.2 in ./.local/lib/python3.9/site-packages (3.9.1)
Collecting webchanges[beautify,use_browser]<3.9.2
  Using cached webchanges-3.9.1-py3-none-any.whl (95 kB)
  Using cached webchanges-3.9-py3-none-any.whl (95 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from webchanges[beautify,use_browser]<3.9.2) (2.25.1)
Requirement already satisfied: lxml in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (4.8.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from webchanges[beautify,use_browser]<3.9.2) (5.3.1)
Requirement already satisfied: msgpack in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (1.0.3)
Requirement already satisfied: html2text in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (2020.1.16)
Requirement already satisfied: platformdirs in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (2.5.2)
Requirement already satisfied: cssselect in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (1.1.0)
Requirement already satisfied: markdown2 in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (2.4.3)
Requirement already satisfied: pyppeteer in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (1.0.2)
Requirement already satisfied: beautifulsoup4 in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (4.11.1)
Requirement already satisfied: jsbeautifier in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (1.14.3)
Requirement already satisfied: cssbeautifier in ./.local/lib/python3.9/site-packages (from webchanges[beautify,use_browser]<3.9.2) (1.14.3)
Requirement already satisfied: soupsieve>1.2 in ./.local/lib/python3.9/site-packages (from beautifulsoup4->webchanges[beautify,use_browser]<3.9.2) (2.3.2.post1)
Requirement already satisfied: six>=1.13.0 in /usr/lib/python3/dist-packages (from cssbeautifier->webchanges[beautify,use_browser]<3.9.2) (1.16.0)
Requirement already satisfied: editorconfig>=0.12.2 in ./.local/lib/python3.9/site-packages (from cssbeautifier->webchanges[beautify,use_browser]<3.9.2) (0.12.3)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (8.1.0)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (4.64.0)
Requirement already satisfied: certifi>=2021 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (2021.10.8)
Requirement already satisfied: websockets<11.0,>=10.0 in ./.local/lib/python3.9/site-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (10.1)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/lib/python3/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (1.4.4)
Requirement already satisfied: urllib3<2.0.0,>=1.25.8 in /usr/lib/python3/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (1.26.5)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/lib/python3/dist-packages (from pyppeteer->webchanges[beautify,use_browser]<3.9.2) (1.6.0)

$ webchanges -v --test 71
2022-05-03 11:06:58,742 cli[139953132902208] DEBUG: webchanges: 3.9.1 Copyright 2020- Mike Borsetti
2022-05-03 11:06:58,742 cli[139953132902208] DEBUG: CPython: 3.9.2 ('default', 'Feb 28 2021 17:03:44') GCC 10.2.1 20210110
2022-05-03 11:06:58,745 cli[139953132902208] DEBUG: System: Linux-5.10.0-13-amd64-x86_64-with-glibc2.31
2022-05-03 11:06:58,745 storage[139953132902208] DEBUG: Run-time SQLite library: 3.34.1
2022-05-03 11:06:58,745 storage[139953132902208] INFO: Opening permanent sqlite3 database file /home/cesar/.cache/webchanges/cache.db
2022-05-03 11:06:58,746 storage[139953132902208] DEBUG: Executing (perm) 'SELECT name FROM sqlite_master WHERE type='table';'
2022-05-03 11:06:58,746 storage[139953132902208] DEBUG: Creating temp sqlite3 database file in memory
2022-05-03 11:06:58,746 storage[139953132902208] DEBUG: Executing (temp) 'CREATE TABLE webchanges (uuid TEXT, timestamp REAL, msgpack_data BLOB)'
2022-05-03 11:06:58,746 main[139953132902208] INFO: Config file is /home/cesar/.config/webchanges/config.yaml
2022-05-03 11:06:58,746 main[139953132902208] INFO: Jobs file is /home/cesar/.config/webchanges/jobs.yaml
2022-05-03 11:06:58,746 main[139953132902208] INFO: Hooks file is /home/cesar/.config/webchanges/hooks.py
2022-05-03 11:06:58,746 main[139953132902208] INFO: Database file is /home/cesar/.cache/webchanges/cache.db
2022-05-03 11:06:58,747 main[139953132902208] INFO: Loading hooks file
2022-05-03 11:06:58,747 main[139953132902208] INFO: Loading jobs from file
2022-05-03 11:06:58,818 main[139953132902208] INFO: Found 83 jobs
2022-05-03 11:06:58,825 storage[139953132902208] INFO: The configuration file /home/cesar/.config/webchanges/config.yaml is missing directive(s); the following default values are being used:
display:
  error: true
  new: true
  unchanged: false
job_defaults:
  shell: {}
  url: {}
report:
  browser:
    enabled: false
    title: '[webchanges] {count} changes: {jobs}'
  email:
    smtp:
      auth: true
      host: localhost
      insecure_password: ''
      port: 25
      starttls: true
      user: ''
  html:
    diff: unified
  ifttt:
    enabled: false
    event: ''
    key: ''
  mailgun:
    api_key: ''
    domain: ''
    enabled: false
    from_mail: ''
    from_name: ''
    region: us
    subject: '[webchanges] {count} changes: {jobs}'
    to: ''
  markdown:
    details: true
    footer: true
    minimal: false
  matrix:
    access_token: ''
    enabled: false
    homeserver: ''
    room_id: ''
  prowl:
    api_key: ''
    application: ''
    enabled: false
    priority: 0
    subject: '[webchanges] {count} changes: {jobs}'
  pushbullet:
    api_key: ''
    enabled: false
  pushover:
    app: ''
    device: null
    enabled: false
    priority: normal
    sound: spacealarm
    user: ''
  run_command:
    command: ''
    enabled: false
  stdout:
    color: true
    enabled: true
  text:
    details: true
    footer: true
    line_length: 75
    minimal: false
  tz: null
  webhook:
    enabled: false
    markdown: false
    max_message_length: null
    webhook_url: ''
  xmpp:
    enabled: false
    insecure_password: ''
    recipient: ''
    sender: ''
See documentation at https://webchanges.readthedocs.io//en/stable/configuration.html
2022-05-03 11:06:58,826 handler[139953132902208] INFO: Job 71: Processing job <url url='https://cloud.google.com/release-notes' ignore_cached=True index_number=71 filter=['beautify', 'html2text', 'strip'] max_tries=2
2022-05-03 11:06:58,826 storage[139953132902208] DEBUG: Executing (perm) 'SELECT msgpack_data, timestamp FROM webchanges WHERE uuid = ? ORDER BY timestamp DESC LIMIT 1' with ('950d9456b6ce57e0b8bfa3c791200214fcbaed6b',)
2022-05-03 11:06:58,829 connectionpool[139953132902208] DEBUG: Starting new HTTPS connection (1): cloud.google.com:443
2022-05-03 11:06:59,730 connectionpool[139953132902208] DEBUG: https://cloud.google.com:443 "GET /release-notes HTTP/1.1" 200 None
2022-05-03 11:06:59,841 filters[139953132902208] INFO: Job 71: Applying filter beautify, subfilter(s) {}
2022-05-03 11:07:00,690 filters[139953132902208] INFO: Job 71: Applying filter html2text, subfilter(s) {}
2022-05-03 11:07:01,646 filters[139953132902208] INFO: Job 71: Applying filter strip, subfilter(s) {}
Google Cloud release notes  |  Documentation
--------------------------------------------
...
```

**Comment by mborsetti** [comment]
Thanks for the report!

Version 3.10.1 should fix this.
