### ISSUE TITLE
[BUG] conflict with lxml v4.9.1

### ISSUE THREAD

**Issue by jprokos** [mborsetti/webchanges#42]
**Describe the bug**
After upgrading **lxml** to **v4.9.1** I am having the following issue.

```
Traceback (most recent call last):
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/filters.py", line 1220, in _get_filtered_elements
    root = etree.fromstring(self.data, self.parser)  # bandit B320: use defusedxml TODO
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1908, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/.pyenv/versions/3.10.5/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/cli.py", line 307, in main
    urlwatch_command.run()
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/command.py", line 688, in run
    self.handle_actions()
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/command.py", line 626, in handle_actions
    self.test_job(self.urlwatch_config.test_job)
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/command.py", line 201, in test_job
    raise job_state.exception
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/handler.py", line 170, in process
    filtered_data = FilterBase.process(filter_kind, subfilter, self, filtered_data)
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/filters.py", line 240, in process
    return filtercls(job_state.job, job_state).filter(data, subfilter)
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/filters.py", line 1313, in filter
    return lxml_parser.get_filtered_data()
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/filters.py", line 1249, in get_filtered_data
    elements = self._get_filtered_elements()
  File "/Users/john/.pyenv/versions/3.10.5/lib/python3.10/site-packages/webchanges/filters.py", line 1227, in _get_filtered_elements
    root = etree.fromstring(self.data, self.parser)  # bandit B320: use defusedxml TODO
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Char 0x0 out of allowed range, line 1, column 2
```

**To Reproduce**

**Expected behavior**

**Screen scrape/screenshots**

**Version info**
Please run ``webchanges -v`` and paste the version information as follows (first 3 lines):
 - webchanges 3.10.2
 - Python 3.10.5 or 3.10.3
 - System macOS-10.15.7-x86_64-i386-64bit

**Additional context**
Downgrading to lxml v4.8.0 resolves this issue for me.

**Comment by mborsetti** [comment]
Thanks for the bug report!

I am trying to track down what changed in lxml 4.9.1 and it's non-obvious. 

What type of data are you passing to the filter? 

If you can even share the YAML for the job that would be wonderful.

**Comment by jprokos** [comment]
--- #### SwimSwam - working 4/10/22 ####
name: 26_SwimSwam - News [NASA Wildcat Aquatics]
url: "https://swimswam.com/feed/#1"
filter:
  - xpath:
      method: xml
      path: '//item/title/text()|//item/description/text()|//item/content:encoded/text()'
      namespaces:
        content: http://purl.org/rss/1.0/modules/content/
      exclude: 'a'
  - keep_lines_containing:
      re: '\bNASA\sWildcat'
  - html2text:
additions_only: true

**Comment by mborsetti** [comment]
Great, thanks!

Unfortunately it's not throwing the error locally (on Windows):
```
C:\>webchanges --jobs jobs-test --test 1
26_SwimSwam - News [NASA Wildcat Aquatics]
------------------------------------------



--
Job tested in 0.57 seconds with webchanges 3.10.2.

C:\>python --version
Python 3.10.5

C:\>pip list | findstr lxml
lxml                          4.9.1
```

I tried it on a Linux box and no errors there either... ???

**Comment by jprokos** [comment]
I have no programming experience so can't really understand the error messages - does it provide any clues?

Give me a day to reinstall and test again before closing

**Comment by mborsetti** [comment]
Thanks.

Nothing is obvious in the lxml changelog: https://lxml.de/4.9/changes-4.9.1.html.

However, I think I *may* have found something at https://lxml.de/FAQ.html#why-can-t-lxml-parse-my-xml-from-unicode-strings. The way XML is handled in webchanges (legacy code) does not seem to conform to the way lxml wants it, and maybe with this release they made other changes that broke this nonstandard way. Maybe, or maybe not.

In any case let me work on an interim release and see if my intuition is correct; hard to know since I still can't reproduce the issue.

**Comment by jprokos** [comment]
Don't know if this is meaningful... since you are saying this is not an issue on Windows, one thing I notice in the lxml change log is that 4.90 is being built with, I think, older versions of libxml2 and libxslt on Windows, and newer versions of those binaries for other OS.

Is it possible that whatever changes happened in 4.9.1 were triggered by an initial change in 4.9.0?

**Comment by mborsetti** [comment]
Yeah, your job works both on Windows 11 and on Ubuntu 22.04 LTS, so ... who knows what's going on.

I've posted a release candidate in the unreleased branch; would you be so kind as to install it and see if my hunch is correct and it does fix your issue?

```
pip install https://github.com/mborsetti/webchanges/archive/unreleased.tar.gz
```

Thanks

**Comment by jprokos** [comment]
Thank you so much for your efforts. Wish I could be of more help.

I installed the Release Candidate but before I could upgrade lxml to 4.9.1 to test run the jobs I mention above ( 26, 27 ), three other jobs ( 30, 31, 32 ) ran and came back with errors... these did not have an issue before installing the RC.

> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Good news is that the initial issue with jobs 26 and 27 are now not reporting an error with the RC and lxml 4.9.1
```
--- #### SwimSwam - working 4/10/22 ####
name: 26_SwimSwam - News [NASA Wildcat Aquatics]
url: "https://swimswam.com/feed/#1"
filter:
  - xpath:
      method: xml
      path: '//item/title/text()|//item/description/text()|//item/content:encoded/text()'
      namespaces:
        content: http://purl.org/rss/1.0/modules/content/
      exclude: 'a'
  - keep_lines_containing:
      re: '\bNASA\sWildcat'
  - html2text:
additions_only: true
--- #### SwimSwam - working 4/10/22 ####
name: 27_SwimSwam - News [Prokos]
url: "https://swimswam.com/feed/#2"
filter:
  - xpath:
      method: xml
      path: '//item/title/text()|//item/description/text()|//item/content:encoded/text()'
      namespaces:
        content: http://purl.org/rss/1.0/modules/content/
      exclude: 'a'
  - keep_lines_containing:
      re: '\bProkos\b'
  - html2text:
additions_only: true
```

But now three other jobs are reporting an error with the RC and 4.9.0 and 4.9.1. Those three jobs are all from the same website.
```
--- #### NASA Registration working 4/17/22 ####
name: 30_NASA - Registration
url: "https://www.teamunify.com/team/isnasa/page/team-registration"
use_browser: false
filter:
  - xpath:
      path: '//*[@id="mainContent"]'
  - html2text:
      method: bs4
  - delete_lines_containing:
      re: '(?i)^(.*)Sign\sin|^(.*)Home|^Questions?|(?i)^Check\sStatus|^\sFacebook|Twitter|Instagram|^\© Copyright|Privacy\sStatement|^\[\]\(https'
  - remove_repeated
additions_only: true
--- #### NASA SC Records - working 4/18/22 ####
name: 31_NASA - SC Records
url: "https://www.teamunify.com/team/isnasa/page/team-info/short-course-yards"
filter:
  - xpath:
      path: '//*[@id="mainContent"]'
  - html2text:
      method: bs4
      parser: html5lib
  - re.sub: '(?m)^[ \t]*'
  - delete_lines_containing:
      re: '(?i)^(.*)Sign\sin|^(.*)Home|^\sFacebook|Twitter|Instagram|^\© Copyright|Privacy\sStatement|^\[\]\(https'
  - strip:
additions_only: true
--- #### NASA Records - working 4/18/22 ####
name: 32_NASA - LC Records
url: "https://www.teamunify.com/team/isnasa/page/team-info/long-course-meters"
filter:
  - xpath:
      path: '//*[@id="mainContent"]'
  - html2text:
      method: bs4
      parser: html5lib
  - re.sub: '(?m)^[ \t]*'
  - delete_lines_containing:
      re: '(?i)^(.*)Sign\sin|^(.*)Home|^\sFacebook|Twitter|Instagram|^\© Copyright|Privacy\sStatement|^\[\]\(https'
  - strip:
additions_only: true
```

[RC and 4.9.1 error.txt](https://github.com/mborsetti/webchanges/files/9086562/RC.and.4.9.1.error.txt)

**Comment by mborsetti** [comment]
Wonderful, thanks for running this and for the excellent data and feedback!  You have been of amazing help.

I tracked down the error in job 30 (and presumably 31 and 32) to the data from the server starting with an XML declaration (`<?xml version="1.0" encoding="UTF-8"?>`) (see https://stackoverflow.com/questions/37592045/is-an-xml-declaration-necessary-in-an-html-document). Now that the code is handling the lxml package correctly, the latter will generate an error as it was expecting "pure" HTML but got an XML header in HTML: an unexpected corner case that I can fix.

I pushed a new release candidate (3.10.3rc1) to the unreleased branch; if you can test it that would be great:

```
pip install https://github.com/mborsetti/webchanges/archive/unreleased.tar.gz
```

**Comment by jprokos** [comment]
That did it!

`webchanges --errors`
Reports no errors or issues from any of my current jobs.
