### ISSUE TITLE
[BUG] TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by CTassisF** [mborsetti/webchanges#72]
**Describe the bug.**
After updating to v3.20.1, webchanges crashes trying to send e-mail.

**Steps to reproduce.**
```
$ cat config.yaml
report:
  email:
    enabled: true
    from: 'webchanges@example.com'
    html: true
    method: 'sendmail'
    sendmail:
      path: '/usr/sbin/sendmail'
    subject: '[webchanges] {count} changes: {jobs}'
    to: 'example@gmail.com'
```

```
$ cat jobs.yaml
command: /usr/bin/dig +short TXT random.m.z0p.org. @8.8.8.8
```

**Expected behavior.**
This same setup was working prior to update to v3.20(.1).

**Screen scrape/screenshots.**
```
$ webchanges -vv
WARNING: Support for Python 3.9 will be ending three years from the date Python 3.10 was released
...
2024-03-16 15:30:21,853 reporters[140258505279296] INFO: Submitting with email (<class 'webchanges.reporters.EMailReporter'>)
2024-03-16 15:30:21,854 _config[140258505279296] DEBUG: load_ssl_context verify=True cert=None trust_env=True http2=False
2024-03-16 15:30:21,855 _config[140258505279296] DEBUG: load_verify_locations cafile='/etc/ssl/certs/ca-certificates.crt'
2024-03-16 15:30:21,868 _config[140258505279296] DEBUG: load_ssl_context verify=True cert=None trust_env=True http2=False
2024-03-16 15:30:21,869 _config[140258505279296] DEBUG: load_verify_locations cafile='/etc/ssl/certs/ca-certificates.crt'
Traceback (most recent call last):
  File "/home/cesar/.local/bin/webchanges", line 8, in <module>
    sys.exit(main())
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/cli.py", line 391, in main
    urlwatch_command.run()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/command.py", line 1084, in run
    self.urlwatcher.close()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/main.py", line 102, in close
    self.report.finish(jobs_file=self.jobs_storage.filename)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/handler.py", line 642, in finish
    ReporterBase.submit_all(self, self.job_states, duration, jobs_file)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/reporters.py", line 277, in submit_all
    subclass(report, cfg, job_states, duration, jobs_files).submit()
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/reporters.py", line 1138, in submit
    mailer.send(msg)
  File "/home/cesar/.local/lib/python3.9/site-packages/webchanges/mailer.py", line 122, in send
    command = [self.sendmail_path, '-oi', msg['To'] + [addr.strip() for addr in msg['To'].split(',')]]
TypeError: can only concatenate str (not "list") to str
```

**Version info.**
```
$ webchanges --detailed-versions
WARNING: Support for Python 3.9 will be ending three years from the date Python 3.10 was released

Software:
• webchanges: 3.20.1
• CPython: 3.9.2 ('default', 'Feb 28 2021 17:03:44') GCC 10.2.1 20210110
• SQLite: 3.34.1

Installed PyPi dependencies:
• beautifulsoup4: 4.12.3
• cryptography: 36.0.1
  - cffi: 1.15.0
  - bcrypt: 3.2.0
• cssbeautifier: 1.15.1
  - jsbeautifier: 1.15.1
  - six: 1.16.0
  - editorconfig: 0.12.4
• cssselect: 1.2.0
• h2: 4.1.0
  - hyperframe: 6.0.1
  - hpack: 4.0.0
• html2text: 2024.2.26
• httpx: 0.27.0
  - anyio: 4.3.0
  - certifi: 2020.6.20
  - idna: 2.10
  - sniffio: 1.3.1
• jsbeautifier: 1.15.1
  - six: 1.16.0
  - editorconfig: 0.12.4
• lxml: 5.1.0
  - cssselect: 1.2.0
  - BeautifulSoup4: 4.12.3
• markdown2: 2.4.13
  - pygments: 2.7.1
  - pygments: 2.7.1
• msgpack: 1.0.8
• platformdirs: 4.2.0
• pyyaml: 5.3.1
• requests: 2.31.0
  - charset-normalizer: 3.3.2
  - idna: 2.10
  - urllib3: 2.1.0
  - certifi: 2020.6.20
  - chardet: 4.0.0

Installed dpkg dependencies:
```

**Comment by mborsetti** [comment]
🤦
